services:
  .dnsmap:
    deploy:
      replicas: 0
    image: ghcr.io/stek29/spoofskipper/dnsmap:69bc1e0ee4c65738e0b6885fbb23fc1581630974
    build:
      context: ./dnsmap
      args:
        REVISION: 69bc1e0ee4c65738e0b6885fbb23fc1581630974

  .zapret:
    image: ghcr.io/stek29/spoofskipper/zapret:v69.5
    build:
      context: ./zapret
      args:
        REVISION: v69.5
    deploy:
      replicas: 0

  .sing-box:
    image: ghcr.io/stek29/spoofskipper/sing-box:v1.10.3
    build:
      context: ./sing-box
      args:
        REVISION: v1.10.1
    deploy:
      replicas: 0
