services:
  dnsmap:
    image: ghcr.io/stek29/spoofskipper/dnsmap:1055eab2de3bc299f57b8c9e16747657a46e4763
    command:
      - -config
      - /config/dnsmap.json
    restart: unless-stopped
    network_mode: service:zapret
    # so it will be killed on zapret restart to force nftables reload
    pid: service:zapret
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./config:/config:ro

  zapret:
    image: ghcr.io/stek29/spoofskipper/zapret:a2c0f81457d87acac30c49fb9ed8a06fb1ea60e0
    environment: {}
    #   NFQWS_DEFAULT_ARGS: '--debug' # example
    #   ZAPRET_PRERUN: 'ip r add default via 127.1.2.3'
    command: "/config/zapret.sh"
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./config:/config:ro
