services:
  unbound:
    image: ghcr.io/stek29/spoofskipper/unbound:$REVISION_UNBOUND-$VERSION_UNBOUND
    network_mode: service:zapret
    restart: always
    environment:
      UNBOUND_FORWARD_TCP: 'yes' # TCP isn't forced to National Domain Name System (yet)
      UNBOUND_DNS64_PREFIX: '64:ff9b:1:7a61:7072:6574::/96'
    volumes:
      - ./config/unbound-dns64:/etc/unbound

  tayga:
    # TODO: switch to custom image
    image: ghcr.io/apalrd/tayga-nat64:0.9.6
    network_mode: service:zapret
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      TAYGA_PREF64: '64:ff9b:1:7a61:7072:6574::/96'
      TAYGA_POOL4: '192.168.240.0/20'
      TAYGA_ADDR4: '192.168.240.1'
      TAYGA_LOG: 'drop reject icmp self dyn'

  zapret:
    image: ghcr.io/stek29/spoofskipper/zapret:$REVISION_ZAPRET-$VERSION_ZAPRET
    environment: {}
    #   NFQWS_DEFAULT_ARGS: '--debug' # example
    #   ZAPRET_PRERUN: 'ip r add default via 127.1.2.3'
    command: "/config/zapret.sh"
    restart: always
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./config:/config:ro

  sing-tun:
    image: ghcr.io/stek29/spoofskipper/sing-box:$REVISION_SINGBOX-$VERSION_SINGBOX
    volumes:
      - ./config/sing:/config:ro
      - ./data:/data:rw
    command: ['run', '-c', '/tmp/sing.json']
    restart: always
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
