services:
  .dnsmap:
    deploy:
      replicas: 0
    image: ghcr.io/stek29/spoofskipper/dnsmap:$REVISION_DNSMAP
    build:
      context: ./dnsmap
      args:
        REVISION: $REVISION_DNSMAP

  .zapret:
    image: ghcr.io/stek29/spoofskipper/zapret:$REVISION_ZAPRET
    build:
      context: ./zapret
      args:
        REVISION: $REVISION_ZAPRET
    deploy:
      replicas: 0

  .sing-box:
    image: ghcr.io/stek29/spoofskipper/sing-box:$REVISION_SINGBOX
    build:
      context: ./sing-box
      args:
        REVISION: $REVISION_SINGBOX
    deploy:
      replicas: 0
