services:
  dnsmap:
    image: ghcr.io/stek29/spoofskipper/dnsmap:69bc1e0ee4c65738e0b6885fbb23fc1581630974
    command:
      - -config
      - /config/dnsmap.json
    restart: unless-stopped
    network_mode: service:zapret
    # so it will be killed on zapret restart to force nftables reload
    pid: service:zapret
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./config:/config:ro

  zapret:
    image: ghcr.io/stek29/spoofskipper/zapret:v69.5
    environment: {}
    #   NFQWS_DEFAULT_ARGS: '--debug' # example
    #   ZAPRET_PRERUN: 'ip r add default via 127.1.2.3'
    command: "/config/zapret.sh"
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./config:/config:ro

  sing-tun:
    image: ghcr.io/stek29/spoofskipper/sing-box:v1.10.3
    volumes:
      - ./config/sing:/config:ro
      - ./data:/data:rw
    command: ['run', '-c', '/tmp/sing.json']
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
