services:
  .dnsmap:
    deploy:
      replicas: 0
    image: ghcr.io/stek29/spoofskipper/dnsmap:69bc1e0ee4c65738e0b6885fbb23fc1581630974
    build:
      context: ./dnsmap
      args:
        REVISION: 69bc1e0ee4c65738e0b6885fbb23fc1581630974

  .zapret:
    image: ghcr.io/stek29/spoofskipper/zapret:a2c0f81457d87acac30c49fb9ed8a06fb1ea60e0
    build:
      context: ./zapret
      args:
        REVISION: a2c0f81457d87acac30c49fb9ed8a06fb1ea60e0
    deploy:
      replicas: 0

  .sing-box:
    image: ghcr.io/stek29/spoofskipper/sing-box:v1.10.1
    build:
      context: ./sing-box
      args:
        REVISION: v1.10.1
    deploy:
      replicas: 0
