services:
  .zapret:
    image: ghcr.io/stek29/spoofskipper/zapret:$REVISION_ZAPRET-$REVISION_ALPINE_IMAGE-$VERSION_ZAPRET
    build:
      context: ./zapret
      args:
        REVISION: $REVISION_ZAPRET
        BASE_VER: $REVISION_ALPINE_IMAGE
    deploy:
      replicas: 0

  .sing-box:
    image: ghcr.io/stek29/spoofskipper/sing-box:$REVISION_SINGBOX-$VERSION_SINGBOX
    build:
      context: ./sing-box
      args:
        REVISION: $REVISION_SINGBOX
    deploy:
      replicas: 0

  .unbound:
    image: ghcr.io/stek29/spoofskipper/unbound:$REVISION_UNBOUND-$REVISION_ALPINE_IMAGE-$VERSION_UNBOUND
    build:
      context: ./unbound
      args:
        REVISION: $REVISION_UNBOUND
        BASE_VER: $REVISION_ALPINE_IMAGE
    deploy:
      replicas: 0
