#!/usr/bin/dumb-init /bin/bash
# shellcheck shell=bash
set -euo pipefail

/nftables.nft
killall dnsmap || :

# shellcheck source=../config/zapret.sh
source "$1"

if [ -n "${ZAPRET_PRERUN:-}" ]; then
  eval "${ZAPRET_PRERUN}"
fi

for cmd in "${NFQWS_INSTANCES[@]}"; do
  echo "starting: $cmd"
  eval nfqws "$cmd" &
done

wait
