#!/usr/bin/dumb-init /bin/bash
# shellcheck shell=bash
set -euo pipefail

/nftables.nft
killall dnsmap || :

# shellcheck source=../config/zapret.sh
source "$1"

if [ -n "${ZAPRET_PRERUN:-}" ]; then
  eval "${ZAPRET_PRERUN}"
fi

combined_cmd="${NFQWS_ARGS[*]}"
for i in "${!NFQWS_INSTANCES[@]}"; do
  cmd="${NFQWS_INSTANCES[$i]}"
  if [ "$i" -gt 0 ]; then
    combined_cmd+=" --new"
  fi
  combined_cmd+=" $cmd"
done

echo "starting: nfqws $combined_cmd"
eval exec nfqws '%s' "$combined_cmd"
