server:
    so-sndbuf: 0
    tls-system-cert: yes
    interface: 0.0.0.0
    interface: ::0
    port: ${UNBOUND_LISTEN_PORT}

    module-config: "dns64 ${UNBOUND_EXTRA_MODULES} iterator"

    dns64-prefix: ${UNBOUND_DNS64_PREFIX}
    dns64-ignore-aaaa: "."
    local-zone: "." block_a

forward-zone:
    name: "."
    forward-addr: ${UNBOUND_FORWARD_ADDR}
    forward-first: no
    forward-tcp-upstream: ${UNBOUND_FORWARD_TCP}
    forward-tls-upstream: ${UNBOUND_FORWARD_TLS}
